/*
@TargetNode='sap-hana'
@GeneratedBy=jogardn
@GenerationDate=08/16/2017 11:46:44
@GenerationHost=JOGARDN-REBUILD
*/

instance of MSFT_nxFileResource as $MSFT_nxFileResource1ref
{
ResourceID = "[nxFile]ExampleFile";
 Type = "File";
 Ensure = "Present";
 Contents = "hello world \n";
 DestinationPath = "/tmp/example";
 ModuleName = "nx";
 SourceInfo = "J:\\GitHub\\SAP-HANA-ARM\\DSC\\ExampleConfiguration.ps1::7::9::nxFile";
 ModuleVersion = "1.0";

 ConfigurationName = "ExampleConfiguration";

};
instance of OMI_ConfigurationDocument


                    {
 Version="2.0.0";
 

                        MinimumCompatibleVersion = "1.0.0";
 

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
 

                        Author="jogardn";
 

                        GenerationDate="08/16/2017 11:46:44";
 

                        GenerationHost="JOGARDN-REBUILD";
 

                        Name="ExampleConfiguration";


                    };
