/*
@TargetNode='sap-hana'
@GeneratedBy=ross
@GenerationDate=08/17/2017 14:33:44
@GenerationHost=SAPCLIENT2
*/

instance of MSFT_nxScriptResource as $MSFT_nxScriptResource1ref
{
ResourceID = "[nxScript]insthana";
 GetScript = "#!/bin/bash\nexit 1";
 TestScript = "#!/bin/bash\nfilecount=`cat /etc/passwd | grep sapadm | wc -l`\nif [ $filecount -gt 0 ]\nthen\n    exit 0\nelse\n    exit 1\nfi\n";
 SourceInfo = "C:\\code5\\SAP-HANA-ARM\\DSC\\ExampleConfiguration.ps1::13::1::nxScript";
 SetScript = "#!/bin/bash\ncd /hana/shared/sapbits/51052325/DATA_UNITS/HDB_LCM_LINUX_X86_64\n/hana/shared/sapbits/51052325/DATA_UNITS/HDB_LCM_LINUX_X86_64/hdblcm -b --configfile /hana/shared/sapbits/hdbinst.cfg";
 ModuleName = "nx";
 ModuleVersion = "1.0";

};

instance of OMI_ConfigurationDocument
{
 Version="1.0.0";
 Author="ross";
 GenerationDate="08/17/2017 14:33:44";
 GenerationHost="SAPCLIENT2";
};

